name: eclipse_thingweb_demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  dart_wot: ^0.34.2
  flutter_launcher_icons: ^0.14.1
  go_router: ^14.3.0
  flutter_settings_ui: ^3.0.1
  shared_preferences: ^2.3.2
  flex_seed_scheme: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/thingweb.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/thingweb.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/images/thingweb-macos.png"
