name: eclipse_thingweb_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dart_wot: ^0.35.0
  fl_chart: ^0.69.0
  flex_seed_scheme: ^3.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_settings_ui: ^3.0.1
  go_router: ^14.3.0
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/thingweb.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/thingweb.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/images/thingweb-macos.png"
